# Define the input for grasp calculation: a point cloud
grasping_pipeline_msgs/GraspInput graspinput
---
# Define the result, if succeeded: defines grasp for gripper
grasping_pipeline_msgs/GraspOutput graspOutput
---
# Define a feedback message
std_msgs/String feedback
